apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: apr-19-w-jim 
  janus-idp.io/tekton: apr-19-w-jim
  backstage.io/kubernetes-id: apr-19-w-jim
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: apr-19-w-jim
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  