apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: apr-19-w-jim
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr-19-w-jim 
  name: apr-19-w-jim
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apr-19-w-jim
    weight: 100 
