apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: apr-19-w-jim
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr-19-w-jim 
  name: apr-19-w-jim
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: apr-19-w-jim 
